service: lambda-ssr-poc

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${env:AWS_DOMAIN}
    createRoute53Record: true
    certificateName: ${env:AWS_DOMAIN}

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      origin: '*'